blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/mihai-ro/loqui/discussions
    about: Please ask questions, share ideas, and discuss features in Discussions.
